// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/hellskater/udhaar-backend/internal/repository"
	"github.com/hellskater/udhaar-backend/internal/router"
	"github.com/hellskater/udhaar-backend/internal/service"
	"github.com/hellskater/udhaar-backend/internal/service/books"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from serve_wire.go:

func newServer(db *gorm.DB, repo repository.Repository, logger *zap.Logger, c *Config) (*Server, error) {
	booksService := books.NewService(repo, logger)
	services := &service.Services{
		Books: booksService,
	}
	routerConfig := provideRouterConfig(c)
	echo := router.Setup(db, repo, services, logger, routerConfig)
	server := &Server{
		L:      logger,
		SS:     services,
		Router: echo,
		Repo:   repo,
	}
	return server, nil
}
