// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"github.com/hellskater/udhaar-backend/internal/repository"
	"github.com/hellskater/udhaar-backend/internal/router/v1"
	"github.com/hellskater/udhaar-backend/internal/service"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from router_wire.go:

func newRouter(db *gorm.DB, repo repository.Repository, ss *service.Services, logger *zap.Logger, config *Config) *Router {
	echo := newEcho(logger, config, repo)
	booksService := ss.Books
	handlers := &v1.Handlers{
		Books:  booksService,
		Repo:   repo,
		Logger: logger,
	}
	router := &Router{
		e:  echo,
		v1: handlers,
	}
	return router
}
